---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: iperf3-server-a
spec:
  replicas: 1
  selectors:
    matchLabels:
      application: iperf3-server-a
  template:
    metadata:
      labels:
        application: iperf3-server-a
    spec:
      containers: 
        - image: quay.io/skupper/simple-iperf
          name: iperf3-server
          command:
            - iperf3
            - "-s"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc-a
  annotations:
    proxy.skupper.github.com/network: skupper
    proxy.skupper.github.com/protocol: tcp
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    application: iperf3-server-a
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc-b
  annotations:
    proxy.skupper.github.com/network: skupper
    proxy.skupper.github.com/protocol: tcp
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    application: iperf3-server-b
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc-c
  annotations:
    proxy.skupper.github.com/network: skupper
    proxy.skupper.github.com/protocol: tcp
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    application: iperf3-server-c
---
