---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: iperf3-server-a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: iperf3-server-a
    spec:
      containers: 
        - image: quay.io/skupper/simple-iperf
          name: iperf3-server
          command:
            - iperf3
            - "-s"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc-a
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    application: iperf3-server-a
---
